### ISSUE TITLE
'../index' 모듈 또는 해당 형식 선언을 찾을 수 없습니다.

### ISSUE THREAD

**Issue by junbae03** [archethic/node-kakaolink#1]
좋은 소스 공유 감사합니다 :D

적용시킬 파일 위치에다가 `npm i `로 설치하였고, 이후 example 소스를 붙여넣기 하니
`'../index' 모듈 또는 해당 형식 선언을 찾을 수 없습니다.` 
라는 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/47444711/128758548-973bf472-9481-4c6f-a83e-1a28fbc68529.png)

**Comment by archethic** [comment]
죄송합니다. 우선 극 초기버전인 1.0.0에서는 잘 작동하는 모듈이며, 최근버전인 1.1.1 버전업데이트를 통해 해당 오류의 해결을 바라보고있습니다.
현재 1.1.1버전을 publish 했으며, 해당오류가 해결되면 이 이슈를 close 하겠습니다.

**Comment by archethic** [comment]
type 관련 오류가 1.1.1에서 해결되었습니다. 해당 이슈를 close합니다.
