### ISSUE TITLE
로그인까지 성공되지만. 전송 400에러가 나옵니다.

### ISSUE THREAD

**Issue by Goodday777** [archethic/node-kakaolink#2]
![image](https://user-images.githubusercontent.com/87592865/129844026-bcc47f6f-a497-41f0-9bdf-32b6cf38cdf2.png)
(send 400 error)

우선 확실히 로그인 loginRes는 성공적으로 받아오는데. 그뒤가 문제군요...
js로 해보았습니다. 
약간 지식이 부족한지라 여쭤봅니다.

![image](https://user-images.githubusercontent.com/87592865/129844652-f8bf4b36-d9d9-40fd-b95a-8d8785102f63.png)

@archethic

**Comment by archethic** [comment]
웹 플랫폼 url,template_args을 다시 확인해주세요

**Comment by Goodday777** [comment]
> 웹 플랫폼 url,template_args을 다시 확인해주세요

이그... 제가 apikey를 혼동 했네요.
바보 같은 질문을 그만 .ㅜㅜ 읔.
항상 감사합니다!
